# Generated by Django 5.2.3 on 2026-03-17 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Prywatna'), ('public', 'Publiczna')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('good', 'Good'), ('used', 'Used')], default='good', max_length=16)),
                ('packaging_state', models.CharField(choices=[('carded', 'Carded'), ('loose', 'Loose'), ('damaged', 'Damaged')], default='carded', max_length=16)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collections_app.collection')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalog.hotwheelsmodel')),
            ],
            options={
                'ordering': ('-is_favorite', 'model__number', 'model__model_name'),
                'unique_together': {('collection', 'model')},
            },
        ),
    ]
