# Generated by Django 5.2.3 on 2026-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('owned', 'Kolekcja'), ('wishlist', 'Wishlist')], default='owned', max_length=12),
        ),
    ]
