# Generated by Django 5.2.3 on 2026-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotWheelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, unique=True)),
                ('toy', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('series_number', models.CharField(blank=True, max_length=32)),
                ('photo_url', models.URLField(blank=True)),
                ('local_photo_path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'Hot Wheels model',
                'verbose_name_plural': 'Hot Wheels models',
                'ordering': ('number', 'model_name'),
            },
        ),
    ]
