# Generated by Django 5.2.3 on 2026-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sync_display_name_with_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catalog_scope_brands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='catalog_scope_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='catalog_scope_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='catalog_scope_year_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='catalog_scope_year_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
