# Generated by Django 5.2.3 on 2026-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_instagram_url_user_tiktok_url_user_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
