from django.urls import path

from .views import (
    CollectionBatchAddView,
    CollectionBatchEditView,
    CollectionBatchDeleteView,
    CatalogQuickAddView,
    CollectionCreateView,
    CollectionDeleteView,
    CollectionDetailView,
    CollectionExportView,
    CollectionImportConfirmView,
    CollectionImportView,
    ImportBacklogListView,
    CollectionItemCreateView,
    CollectionItemDeleteView,
    CollectionItemUpdateView,
    CollectionUpdateView,
    DashboardView,
    CollectionStatsView,
    CommunityView,
    PublicCollectionListView,
    WantedCreateView,
    WantedDeleteView,
    WantedListView,
    WantedUpdateView,
)

app_name = 'collections'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('stats/', CollectionStatsView.as_view(), name='stats'),
    path('community/', CommunityView.as_view(), name='community'),
    path('public/', PublicCollectionListView.as_view(), name='public-collections'),
    path('wanted/', WantedListView.as_view(), name='wanted-list'),
    path('wanted/new/', WantedCreateView.as_view(), name='wanted-create'),
    path('wanted/<int:pk>/edit/', WantedUpdateView.as_view(), name='wanted-update'),
    path('wanted/<int:pk>/delete/', WantedDeleteView.as_view(), name='wanted-delete'),
    path('import/', CollectionImportView.as_view(), name='collection-import'),
    path('import/confirm/', CollectionImportConfirmView.as_view(), name='collection-import-confirm'),
    path('import/backlog/', ImportBacklogListView.as_view(), name='import-backlog'),
    path('batch-add/', CollectionBatchAddView.as_view(), name='batch-add'),
    path('quick-add/', CatalogQuickAddView.as_view(), name='quick-add'),
    path('new/', CollectionCreateView.as_view(), name='collection-create'),
    path('<int:pk>/', CollectionDetailView.as_view(), name='collection-detail'),
    path('<int:pk>/items/batch-edit/', CollectionBatchEditView.as_view(), name='item-batch-edit'),
    path('<int:pk>/items/batch-delete/', CollectionBatchDeleteView.as_view(), name='item-batch-delete'),
    path('<int:pk>/export/<str:fmt>/', CollectionExportView.as_view(), name='collection-export'),
    path('<int:pk>/edit/', CollectionUpdateView.as_view(), name='collection-update'),
    path('<int:pk>/delete/', CollectionDeleteView.as_view(), name='collection-delete'),
    path('<int:collection_pk>/items/new/', CollectionItemCreateView.as_view(), name='item-create'),
    path('items/<int:pk>/edit/', CollectionItemUpdateView.as_view(), name='item-update'),
    path('items/<int:pk>/delete/', CollectionItemDeleteView.as_view(), name='item-delete'),
]
