from django.urls import path

from .views import (
    CollectionBatchAddView,
    CollectionBatchEditView,
    CollectionBatchDeleteView,
    CatalogQuickAddView,
    CollectionCreateView,
    CollectionDeleteView,
    CollectionDetailView,
    CollectionExportView,
    CollectionImportConfirmView,
    CollectionImportView,
    ImportBacklogListView,
    CollectionItemCreateView,
    CollectionItemDeleteView,
    CollectionItemQuantityAdjustView,
    CollectionItemUpdateView,
    CollectionUpdateView,
    DashboardView,
    CollectionStatsView,
    CommunityView,
    PublicCollectionListView,
    WarehouseLocationCreateView,
    WarehouseLocationDeleteView,
    WarehouseLocationDetailView,
    WarehouseLocationListView,
    WarehouseItemRelocateView,
    WarehouseQuickAttachView,
    WarehouseQuickSlotAttachView,
    WarehouseSlotClearView,
    WarehouseSlotMoveView,
    WarehouseSlotAssignView,
    WarehouseLocationUpdateView,
    WantedCreateView,
    WantedDeleteView,
    WantedListView,
    WantedUpdateView,
)

app_name = 'collections'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('stats/', CollectionStatsView.as_view(), name='stats'),
    path('warehouse/', WarehouseLocationListView.as_view(), name='warehouse-list'),
    path('warehouse/new/', WarehouseLocationCreateView.as_view(), name='warehouse-create'),
    path('warehouse/<int:pk>/', WarehouseLocationDetailView.as_view(), name='warehouse-detail'),
    path('warehouse/<int:pk>/quick-attach/<int:item_pk>/', WarehouseQuickAttachView.as_view(), name='warehouse-quick-attach'),
    path('warehouse/<int:pk>/quick-attach-slot/<int:row>/<int:column>/<int:item_pk>/', WarehouseQuickSlotAttachView.as_view(), name='warehouse-quick-slot-attach'),
    path('warehouse/<int:pk>/slot/<int:row>/<int:column>/assign/', WarehouseSlotAssignView.as_view(), name='warehouse-slot-assign'),
    path('warehouse/<int:pk>/slot/<int:row>/<int:column>/move/<int:item_pk>/', WarehouseSlotMoveView.as_view(), name='warehouse-slot-move'),
    path('warehouse/<int:pk>/slot/clear/<int:item_pk>/', WarehouseSlotClearView.as_view(), name='warehouse-slot-clear'),
    path('warehouse/<int:pk>/items/<int:item_pk>/relocate/', WarehouseItemRelocateView.as_view(), name='warehouse-item-relocate'),
    path('warehouse/<int:pk>/edit/', WarehouseLocationUpdateView.as_view(), name='warehouse-update'),
    path('warehouse/<int:pk>/delete/', WarehouseLocationDeleteView.as_view(), name='warehouse-delete'),
    path('community/', CommunityView.as_view(), name='community'),
    path('public/', PublicCollectionListView.as_view(), name='public-collections'),
    path('wanted/', WantedListView.as_view(), name='wanted-list'),
    path('wanted/new/', WantedCreateView.as_view(), name='wanted-create'),
    path('wanted/<int:pk>/edit/', WantedUpdateView.as_view(), name='wanted-update'),
    path('wanted/<int:pk>/delete/', WantedDeleteView.as_view(), name='wanted-delete'),
    path('import/', CollectionImportView.as_view(), name='collection-import'),
    path('import/confirm/', CollectionImportConfirmView.as_view(), name='collection-import-confirm'),
    path('import/backlog/', ImportBacklogListView.as_view(), name='import-backlog'),
    path('batch-add/', CollectionBatchAddView.as_view(), name='batch-add'),
    path('quick-add/', CatalogQuickAddView.as_view(), name='quick-add'),
    path('new/', CollectionCreateView.as_view(), name='collection-create'),
    path('<int:pk>/', CollectionDetailView.as_view(), name='collection-detail'),
    path('<int:pk>/items/batch-edit/', CollectionBatchEditView.as_view(), name='item-batch-edit'),
    path('<int:pk>/items/batch-delete/', CollectionBatchDeleteView.as_view(), name='item-batch-delete'),
    path('<int:pk>/export/<str:fmt>/', CollectionExportView.as_view(), name='collection-export'),
    path('<int:pk>/edit/', CollectionUpdateView.as_view(), name='collection-update'),
    path('<int:pk>/delete/', CollectionDeleteView.as_view(), name='collection-delete'),
    path('<int:collection_pk>/items/new/', CollectionItemCreateView.as_view(), name='item-create'),
    path('items/<int:pk>/edit/', CollectionItemUpdateView.as_view(), name='item-update'),
    path('items/<int:pk>/adjust-quantity/', CollectionItemQuantityAdjustView.as_view(), name='item-adjust-quantity'),
    path('items/<int:pk>/delete/', CollectionItemDeleteView.as_view(), name='item-delete'),
]
